[package]
name = "metarust_trace_plugin"
version = "0.0.1"
authors = ["Fedcomp"]
edition = "2018"
publish = false

[lib]
crate-type = ["dylib"]

[features]
strict = [] # Treat warnings as a build error

[dependencies]
metarust = { path = "metarust" }
