[package]
name = "metarust"
version = "0.1.0"
authors = ["Fedcomp <aglergen@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
