[package]
name = "metarust"
version = "0.0.1"
authors = ["Fedcomp"]
edition = "2018"

[dependencies]
cstr-macro = "0.1.0"
metamod-bindgen = { path = "../metamod_bindgen" }
metamod-sys = { path = "../metamod_sys" }
hlsdk-sys = { path = "../hlsdk_sys" }
ctor = "0.1.9"